<?php

if ((isset($this->list)) && (!count($this->list))) {
    echo(
    '<div class="well">
            <p class="text-center">Ainda não existem posts para ver, comece postando um...</p>
        </div>'
    );
}
?>

<!-- posts -->
<?php foreach ($this->list as $post) {
    $getGostei = false;
    foreach ($this->gostei as $gostei) {
        if ((int)$gostei['postId'] == $post->getPostId()) {
            $getGostei = true;
        }
    }
    ?>
    <!-- social-feed-box -->
    <div class="social-feed-box">
        <!-- social-action -->
        <div class="pull-right social-action dropdown">
            <button data-toggle="dropdown" class="dropdown-toggle btn-white">
                <i class="fa fa-angle-down"></i>
            </button>
            <ul class="dropdown-menu m-t-xs">
                <li><a href="<?php echo($this->url('post') . '/view/' . $post->getPostId()); ?>">Visualizar</a></li>
            </ul>
        </div>
        <!-- end social-action -->
        <!-- social-avatar -->
        <div class="social-avatar">
            <a href="<?php echo($this->url('profile') . '/' . $post->getUserId()); ?>" class="pull-left">
                <img onerror="this.src='<?php echo($this->basePath() . '/img/not-found/not-found-picture-post-user.png'); ?>'" alt="image" src="<?php echo($this->basePath() . '/upload/profile/img_' . $post->getUserPicture());?>">
            </a>

            <div class="media-body">
                <a href="<?php echo($this->url('profile') . '/' . $post->getUserId()); ?>">
                    <?php echo($post->getUserName()); ?>
                </a>
                <span class="badge badge-info float-right"><?php echo($post->getPostTypeName()); ?></span>
                <i class="hide fa <?php echo($post->getPostClassification()); ?>"></i>
                <i class="hide fa <?php echo($post->getPostPrivacity()); ?>"></i>
                <small class="text-muted"><?php echo($post->getPostDate()); ?></small>
            </div>
        </div>
        <!-- end social-avatar -->
        <div class="clearfix"></div>
        <!-- social-body -->
        <div class="social-body">
            <p>
                <?php echo($post->getPostContent()); ?>
            </p>
            <?php
            $img = $post->getPostPicture();
            if ($img) {
                ?>
                <img src="<?php echo($this->basePath() . '/upload/posts/img_' . $img . '" class="img-responsive"'); ?>"
                     onerror="this.src='<?php echo($this->basePath() . '/img/not-found/not-found-picture-post.jpg'); ?>'">
            <?php
            }
            ?>
            <div class="btn-group post-btn-actions">
                <button
                    class="btn btn-xs btn-gostei <?php echo($getGostei ? 'btn-primary' : 'btn-white'); ?>"
                    data-postid="<?php echo($post->getPostId()); ?>">
                    <i class="fa fa-heart"></i> Gostei
                    <span class="btn-gostei-span-count-<?php echo($post->getPostId()); ?>">
                        (<?php echo($post->getPostGosteiCount()) ?>)
                    </span>
                </button>
                <!--<button
                    class="btn btn-white btn-xs btn-comments"
                    data-postid="<?php echo($post->getPostid()); ?>">
                    <i class="fa fa-comments"></i> Comment
                </button>-->
                <button class="btn btn-white btn-xs"><i class="fa fa-share"></i> Share</button>
            </div>
        </div>
        <!-- end social-body -->
        <!-- social-footer -->
        <div class="social-footer post-comments posts-comments-<?php echo($post->getPostid()); ?>">
            <!-- social-comment -->
            <div class="social-comment comment-infos">
                <a href="#" class="comment-link-getcomments open" data-postid="<?php echo($post->getPostId()); ?>">
                    <small>
                        <span class="actionShow">Ver</span>
                        <span class="actionHide">Ocultar</span>
                        <span class="comment-link-getcomments-count-<?php echo($post->getPostId()); ?>">
                            <?php echo($post->getPostCommentsCount()) ?>
                        </span>
                        comentários...
                        <i class="fa fa-angle-down actionShow"></i>
                        <i class="fa fa-angle-up actionHide"></i>
                    </small>
                </a>
            </div>
            <!-- end social-comment -->
            <div class="comment-container comment-container-<?php echo($post->getPostid()); ?>">
                <!-- social-comment -->
                <div class="social-comment">
                    <div class="sk-spinner sk-spinner-cube-grid">
                        <div class="sk-cube"></div>
                        <div class="sk-cube"></div>
                        <div class="sk-cube"></div>
                        <div class="sk-cube"></div>
                        <div class="sk-cube"></div>
                        <div class="sk-cube"></div>
                        <div class="sk-cube"></div>
                        <div class="sk-cube"></div>
                        <div class="sk-cube"></div>
                    </div>
                </div>
                <!-- end social-comment -->
            </div>
            <!-- social-comment -->
            <div class="social-comment comment-add">
                <a href="" class="pull-left">
                    <img
                        alt="<?php echo($this->identity()->getName()); ?>"
                        title="<?php echo($this->identity()->getName()); ?>"
                        src="<?php echo($this->basePath() . '/upload/profile/img_' . $this->identity()->getPicture()); ?>"
                        onerror="this.src='<?php echo($this->basePath() . '/img/not-found/not-found-picture-post-user-lg.png'); ?>'">
                </a>

                <div class="media-body">
                    <textarea class="form-control input-comment" data-postid="<?php echo($post->getPostid()); ?>" placeholder="Write comment..."></textarea>
                </div>
            </div>
            <!-- end social-comment -->
        </div>
        <!-- end social-footer -->
    </div>
    <!--end social-feed-box -->
<?php
}
?>

<script defer src="<?php echo($this->basePath() . '/'); ?>js/feed.js"></script>
<script defer src="<?php echo($this->basePath() . '/'); ?>js/gostei.js"></script>