<!-- postar -->
<div class="col-md-8 col-md-offset-2">

    <form
        class="social-feed-box clear postar active"
        action="<?php echo($this->url('post') . "/inserir");?>"
        method="POST" enctype="multipart/form-data">

    <div class="social-body clearfix">

        <input id="post-type" type="hidden" name="type" value="1">

        <div class="postar-div-btn-type">
            <button id="btn-postar-texto" class="postar-btn-type btn btn-primary btn-xs" type="button">
                <i class="fa fa-pencil"></i>&nbsp;Texto
            </button>
            <button id="btn-postar-foto" class="postar-btn-type btn btn-default btn-xs" type="button">
                <i class="fa fa-picture-o"></i>&nbsp;Foto
            </button>
        </div>
        <div class="form-group postar-principal clearfix">
            <textarea
                required
                name="content"
                placeholder="poste algo..."
                class="form-control postar-textarea"></textarea>
        </div>

        <div class="row postar-itens-tipo postar-foto">
            <div class="form-group clearfix">
                <label class="control-label col-sm-2">Foto:</label>
                <div class="col-sm-10">
                    <input type="file" name="picture" id="post-foto"/>
                </div>
            </div>
        </div>

        <a
            id="postar-btn-options"
            role="button"
            data-toggle="collapse"
            href="#collapseExample"
            aria-expanded="false"
            aria-controls="collapseExample">
            Opções Avançadas...
        </a>

        <div class="row">
            <div class="collapse" id="collapseExample">
                <div class="form-group postar-privacidade">
                    <label for="inputPassword3" class="col-sm-2 control-label">Privacidade</label>
                    <div class="col-sm-10">
                        <div class="radio radio-info radio-inline">
                            <input type="radio" id="privacidade1" value="1" name="privacity" checked="">
                            <label for="privacidade1"> Público </label>
                        </div>
                        <div class="radio radio-info radio-inline">
                            <input type="radio" id="privacidade2" value="2" name="privacity">
                            <label for="privacidade2"> Amigos </label>
                        </div>
                    </div>
                </div>

                <div class="form-group postar-privacidade">
                    <label for="inputPassword3" class="col-sm-2 control-label">Classificação</label>
                    <div class="col-sm-10">
                        <div class="radio radio-info radio-inline">
                            <input type="radio" id="classification1" value="1" name="classification" checked="">
                            <label for="classification1"> Livre </label>
                        </div>
                        <div class="radio radio-info radio-inline">
                            <input type="radio" id="classification2" value="2" name="classification">
                            <label for="classification2"> 18+ </label>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="postar-btn-action">
            <button class="btn btn-success btn-sm" type="submit">
                <i class="fa fa-pencil"></i>&nbsp;Postar
            </button>
            <button id="postarCancelar" class="btn btn-default btn-sm" type="reset">
                <i class="fa fa-close"></i>&nbsp;Cancelar
            </button>
        </div>
    </div>
    </form>
</div>
<div class="clearfix"></div>
<!-- end postar -->

