<!-- begin content -->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <!-- begin content -->


        <div class="col-lg-9 col-lg-offset-2">
            <?php
            echo($this->partial('post/index/feed-partial', array('list' => $list, 'gostei' => $this->gostei)));
            ?>
        </div>

        <!-- end content -->
    </div>
</div>
<!-- end content -->

<script defer src="<?php echo($this->basePath() . '/'); ?>js/post-view.js"></script>