<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Minhas Notificações</h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Notificações</a>
            </li>
            <li class="active">
                <strong>Todas</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<!-- begin content -->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <!-- begin content -->

        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">

                    <?php
                    if (!count($this->notifications)) {
                        ?>
                        <div class="timeline-item">
                            <div class="row">
                                <div class="col-xs-3 date">

                                </div>
                                <div class="col-xs-7 content">
                                    <p class="m-b-xs">
                                        <strong>Sem notificações</strong>
                                    </p>

                                    <p>Você ainda não tem notificações.</p>

                                </div>
                            </div>
                        </div>
                        <?php
                    } else {

                        foreach ($this->notifications as $notification) { ?>

                            <div class="timeline-item">
                                <div class="row">
                                    <div class="col-xs-3 date">
                                        <i class="<?php echo($notification->getNotificationActionIcon()); ?>"></i>
                                        <?php echo(date('d/m', strtotime($notification->getNotificationDate()))); ?>
                                        <br>
                                        <small class="text-navy"><?php echo(date('H:i',
                                                strtotime($notification->getNotificationDate()))); ?></small>
                                    </div>
                                    <div class="col-xs-7 content">
                                        <p class="m-b-xs">
                                            <strong><?php echo($notification->getNotificationActionName()); ?></strong>
                                        </p>

                                        <img alt="image" class="img-circle user-picture-sm"
                                             src="<?php echo(
                                                 $this->basePath() . '/upload/profile/img_' . $notification->getNotificationAuthorPicture()
                                             ); ?>"
                                             onerror=
                                             "this.src='<?php echo(
                                                 $this->basePath() . '/img/not-found/not-found-picture-post-user-lg.png'
                                             ); ?>'">
                                        <a class="notification-item-userProfile-link"
                                           href="<?php echo($this->url('profile') . '/' . $notification->getNotificationAuthorId()); ?>">
                                            <?php echo($notification->getNotificationAuthorName()); ?>
                                        </a>
                                        <?php echo($notification->getNotificationActionOutput()); ?>
                                        <a class="notification-item-post-link"
                                           href="<?php echo($this->url('post') . '/view/' . $notification->getNotificationPostId()); ?>">
                                            <?php if ($notification->getNotificationActionOutput() != 'está seguindo você') {
                                                echo('post');
                                            } ?>
                                        </a>.

                                    </div>
                                </div>
                            </div>
                            <?php
                        }
                    }
                    ?>
                </div>
            </div>
        </div>


        <!-- end content -->
    </div>
</div>
<!-- end content -->