<?php foreach ($comments as $comment) { ?>
    <!-- social-comment -->
    <div class="social-comment">
        <a href="" class="pull-left">
            <img alt="image" src="<?php echo($this->basePath() . '/'); ?>img/a1.jpg">
        </a>

        <div class="media-body">
            <a href="#">
                Andrew Williams
            </a>
            <?php echo($comment->getContent()); ?>
            <br>
            <small class="text-muted"><?php echo($comment->getDate()); ?></small>
        </div>
    </div>
    <!-- end social-comment -->
<?php } ?>