<?php

namespace Profile\Entity;

use Auth\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * AuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
}
