<?php

namespace Profile\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{

    public function searchByName($strName)
    {
        $query = $this->_em->createQuery(
            'SELECT u
              FROM Profile\Entity\Profile u
              WHERE u.name LIKE "%' . $strName .'%"'
        );
        return $query->getResult();
    }
}
