<?php
/**
 * @var $form \Zend\Form\Form
 */
$form = $this->form;

if ($this->success)
    echo '<div class="alert alert-success">'.$this->success[0].'<button type="button" class="close" data-dismiss="alert">×</button></div>';

if ($this->error)
    echo '<div class="alert alert-warning">'.$this->error[0].'<button type="button" class="close" data-dismiss="alert">×</button></div>';

$this->formElementErrors()
    ->setMessageOpenFormat ('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">×</button>')
    ->setMessageCloseString ('</div>')
    ->render ($form);

$form->setAttribute('action', $this->url('profile-editar'));

$form->prepare();
?>
<div class="ibox float-e-margins">
    <div class="ibox-title">
        <h5>Editar Perfil</small></h5>
        <div class="ibox-tools">
            <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-wrench"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#">Config option 1</a>
                </li>
                <li><a href="#">Config option 2</a>
                </li>
            </ul>
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a>
        </div>
    </div>
    <div class="ibox-content">
        <?php echo $this->form()->openTag($form); ?>
            <div class="form-group"><label class="col-sm-2 control-label">Nome</label>

                <div class="col-sm-10">
                    <?php echo $this->formRow($form->get('name')->setAttribute('class', 'form-control')); ?>
                </div>
            </div>
            <div class="hr-line-dashed"></div>
            <div class="form-group"><label class="col-sm-2 control-label">Username</label>

                <div class="col-sm-10">
                    <?php echo $this->formRow($form->get('username')->setAttribute('class', 'form-control')); ?>
                </div>
            </div>
            <div class="hr-line-dashed"></div>
            <div class="form-group"><label class="col-sm-2 control-label">Email</label>

                <div class="col-sm-10">
                    <?php echo $this->formRow($form->get('email')->setAttribute('class', 'form-control')); ?>
                </div>
            </div>
            <div class="hr-line-dashed"></div>
            <div class="form-group"><label class="col-sm-2 control-label">Foto</label>

                <div class="col-sm-10">
                    <?php echo $this->formRow($form->get('picture')->setAttribute('class', 'form-control')); ?>
                </div>
            </div>
            <div class="hr-line-dashed"></div>
            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-2">
                    <button class="btn btn-white" type="reset">Cancelar</button>
                    <?php echo $this->formRow($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>
                </div>
            </div>
        </form>
    </div>
</div>