<?php

namespace Gostei\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GosteiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GosteiRepository extends EntityRepository
{
}
