<?php

namespace Gostei\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VwGosteiCountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VwGosteiCountRepository extends EntityRepository
{
}
