<?php
if ((isset($this->friends)) && (!count($this->friends))) {
    ?>
    <div class="row">
        <div class="well">
            <h3 class="text-center">Sem usuários a mostrar...</h3>
        </div>
    </div>
<?php
}


foreach ($this->friends as $friend) {
    ?>
    <div class="col-lg-3">
        <div class="contact-box center-version">

            <a href="<?php echo($this->url('profile') . '/' . $friend->getFollowerId()); ?>">

                <img
                    alt="image"
                    class="img-circle"
                    src="<?php echo($this->basePath() . '/upload/profile/img_' . $friend->getFollowerPicture()); ?>"
                    onerror="this.src='<?php echo($this->basePath() . '/img/not-found/not-found-picture-post-user.png'); ?>'">


                <h3 class="m-b-xs"><strong><?php echo($friend->getFollowerName()); ?></strong></h3>

                <div class="font-bold">Graphics designer</div>
                <address class="m-t-md">
                    <strong>Twitter, Inc.</strong><br>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    <abbr title="Phone">P:</abbr> (123) 456-7890
                </address>

            </a>

            <div class="contact-box-footer">
                <div class="m-t-xs btn-group">
                    <a class="btn btn-xs btn-white"><i class="fa fa-phone"></i> Call </a>
                    <a class="btn btn-xs btn-white"><i class="fa fa-envelope"></i> Email</a>
                    <a class="btn btn-xs btn-white"><i class="fa fa-user-plus"></i> Follow</a>
                </div>
            </div>

        </div>
    </div>
<?php
}
?>