<!-- begin content -->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <!-- begin content -->

        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content text-center p-md">

                        <h2>
                            <span class="text-navy">Gerencie sua lista de seguindo,</span>
                            aqui está todos os usuários que você está seguindo.
                        </h2>

                        <div class="btn-group">
                            <button class="btn btn-white">A</button>
                            <button class="btn btn-white active">B</button>
                            <button class="btn btn-white">C</button>
                            <button class="btn btn-white">D</button>
                        </div>


                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <?php
                echo($this->partial('friend/index/following-partial', array('friends' => $this->friends)));
                ?>
            </div>
        </div>

        <!-- end content -->
    </div>
</div>
<!-- end content -->