<?php

namespace Comment\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getCountComments($arrPostId)
    {
        if ($arrPostId) {
            $query = $this->_em->createQuery(
                'SELECT COUNT(u.postId) , u.postId FROM Comment\Entity\Comment u WHERE u.postId IN ('
                . $arrPostId . ')');
            return $query->getResult();
        }
        return array();
    }
}
