<?php

namespace Comment\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VwCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VwCommentRepository extends EntityRepository
{
}
