<?php

namespace Notification\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VwNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VwNotificationRepository extends EntityRepository
{

    /**
     * Metodo responsavel por retornar todas as notificacoes novas por data decrescente
     *
     * @param $intUserId
     * @return array
     */
    public function getNewNotifications($intUserId)
    {
        $query = $this->_em->createQuery(
            'SELECT u FROM Notification\Entity\VwNotification u
            WHERE u.notificationPostAuthorId = ' . $intUserId . '
            AND u.notificationAuthorId <> ' . $intUserId . '
            AND u.notificationStatus = 0
            ORDER BY u.notificationDate DESC'
        );

        return $query->getResult();
    }


    /**
     * Metodo responsavel por retornar todas as notficacoes por data decrescente
     *
     * @param $intUserId
     * @return array
     */
    public function getAllNotifications($intUserId)
    {

        $query = $this->_em->createQuery(
            'SELECT u FROM Notification\Entity\VwNotification u
            WHERE (u.notificationPostAuthorId = ' . $intUserId . '
            AND u.notificationAuthorId <> ' . $intUserId . ')
            ORDER BY u.notificationDate DESC'
        );

        return $query->getResult();
    }
}
