<?php

namespace Notification\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VwNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VwNotificationRepository extends EntityRepository
{
}
