<?php

namespace Friend\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FollowingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowingRepository extends EntityRepository
{
}
