<?php

namespace Friend\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FollowersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowersRepository extends EntityRepository
{
}
