<?php

namespace Friend\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendRepository extends EntityRepository
{
    /**
     * @param $arrFriendId
     * @param $intUserId
     * @return array
     */
    public function getFriend($arrFriendId, $intUserId)
    {
        $query = $this->_em->createQuery(
            'SELECT u.friendId
              FROM Friend\Entity\Friend u
              WHERE u.friendIdIN ('. $arrFriendId .')
              AND u.userId = ' . $intUserId
        );
        return $query->getResult();
    }
}
