<?php

namespace Friend\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VwFriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VwFriendRepository extends EntityRepository
{
}
